version: '3.6'

services:
  crypto-currency-tracker-django:
    container_name: crypto_tracker_django
    build:
      context: .
    restart: always
    command: bash -c "python manage.py runserver 0.0.0.0:8093 & python manage.py start_btc_tracker & python manage.py start_eth_tracker"
    volumes:
      - .:/opt/webapp
    env_file:
      - .env
    ports:
      - "8093:8093"