# Generated by Django 5.1.3 on 2024-12-03 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCBuyingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_rate', models.FloatField(default=1, help_text='Your BTC buying rate (1 BTC Price).')),
                ('buying_amount', models.FloatField(default=0.0, help_text='Your BTC buying amount in CAD.')),
                ('profit_target', models.FloatField(default=0.0, help_text='The target profit(in CAD) for selling BTC.')),
                ('date', models.DateField(default=datetime.date.today)),
                ('sold', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'BTC Buying Record',
                'verbose_name_plural': 'BTC Buying Records',
            },
        ),
        migrations.CreateModel(
            name='BTCPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buying_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('recommendation', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'BTC Price',
                'verbose_name_plural': 'BTC Prices',
            },
        ),
        migrations.CreateModel(
            name='BTCTrackerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_target', models.FloatField(default=0.0, help_text='The price below which to buy BTC.')),
                ('fetch_data_duration', models.IntegerField(default=30, help_text='Sleep time after API call in second')),
                ('send_selling_alert', models.BooleanField(default=True)),
                ('send_buying_alert', models.BooleanField(default=True)),
                ('alert_delay', models.IntegerField(default=30, help_text='The delay of sending email in minutes')),
                ('data_limit', models.IntegerField(default=2880, help_text='Max records will be stored')),
                ('records_to_display_in_chart', models.IntegerField(default=100, help_text='Last X records to display in chart')),
                ('last_email_time', models.DateTimeField(blank=True, help_text='Last time an email was sent.', null=True)),
            ],
            options={
                'verbose_name': 'BTC Tracker Settings',
                'verbose_name_plural': 'BTC Tracker Settings',
            },
        ),
    ]
