# Generated by Django 5.1.3 on 2024-12-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcprice',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
