# Generated by Django 5.1.3 on 2024-11-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buying_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('my_buying_price', models.FloatField(default=0.0, help_text='Your BTC buying price.')),
                ('buying_target_threshold', models.FloatField(default=0.0, help_text='The difference of selling price and your buying price')),
                ('buying_target', models.FloatField(default=0.0, help_text='The target profit(in CAD) for selling BTC.')),
                ('selling_target', models.FloatField(default=0.0, help_text='The price below which to buy BTC.')),
                ('recommendation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
