# Generated by Django 5.1.3 on 2024-11-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buying_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('recommendation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BTCTrackerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_buying_price', models.FloatField(default=0.0, help_text='Your BTC buying price.')),
                ('selling_target_threshold', models.FloatField(default=1250.61, help_text='The difference of current selling price and your buying price')),
                ('profit_target', models.FloatField(default=0.0, help_text='The target profit(in CAD) for selling BTC.')),
                ('buying_target', models.FloatField(default=0.0, help_text='The price below which to buy BTC.')),
                ('fetch_data_duration', models.IntegerField(default=15, help_text='Sleep time after API call in second')),
                ('send_selling_alert', models.BooleanField(default=True)),
                ('send_buying_alert', models.BooleanField(default=True)),
                ('alert_delay', models.TimeField(blank=True, help_text='The delay of sending email', null=True)),
                ('last_email_time', models.DateTimeField(blank=True, help_text='Last time an email was sent.', null=True)),
            ],
            options={
                'verbose_name': 'BTC Tracker Config',
                'verbose_name_plural': 'BTC Tracker Config',
            },
        ),
    ]
