# Generated by Django 5.1.3 on 2024-11-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btctrackerconfig',
            name='alert_delay',
            field=models.IntegerField(blank=True, help_text='The delay of sending email in minutes', null=True),
        ),
    ]
