# Generated by Django 5.1.3 on 2024-11-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tracker', '0003_alter_btctrackerconfig_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='btctrackerconfig',
            name='fetch_data_duration',
            field=models.IntegerField(default=15, help_text='Sleep time after API call in second'),
        ),
    ]
