# Generated by Django 5.1.3 on 2024-11-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tracker', '0004_btctrackerconfig_fetch_data_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='btctrackerconfig',
            name='last_email_time',
            field=models.DateTimeField(blank=True, help_text='Last time an email was sent.', null=True),
        ),
    ]
