# Generated by Django 5.1.3 on 2024-11-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tracker', '0005_btctrackerconfig_last_email_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='btctrackerconfig',
            name='send_email_alert',
            field=models.BooleanField(default=True),
        ),
    ]
